codecov:
  strict_yaml_branch: master
  notify:
    require_ci_to_pass: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - "master"
ignore:
  - "setup.py"
coverage:
  precision: 2
  range: 80...100
  round: down
  status:
    changes: off
    project: off
    patch: off
