language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip3 install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - pytest
virtualenv:
  system_site_packages: true