[tool.black]
line-length = 79
target-version = ['py36']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | tests
    | rare_cases
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.isort]
multi_line_output=4
include_trailing_comma=True
force_grid_wrap=0
use_parentheses=True
line_length=79
skip=rare_cases,tests

[tool.unimport]
folders = [
    '.*(tests)',
    '.*(rare_cases)',
]
files = [
    '.*(__init__.py)',
]